'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic


    Partial Public Class LoginColumnType
        'Public Property ID As Integer
        'Public Property IDNumber As Integer
        'Public Property Heading As String
        'Public Property ControlName As String
        'Public Property ControlType As Nullable(Of Integer)
        'Public Property Frontend As Nullable(Of Integer)
        'Public Property Order As Nullable(Of Integer)
        Public Sub New(ByVal nID As Integer)
            ID = nID
        End Sub

        Public ID As Integer
        Public BackendDisplayValue As String
        Public ColumnName As String
        Public ControlMaxLength As Integer
        Public ControlWidth As Integer
        Public DisplayName As String
        Public SQLType As String = "varchar(50)"
        Public ControlReference As String
        Public ControlType As String
        Public IncludeSelectStatement As Boolean = True

    End Class
