'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class backendnew
    
    '''<summary>
    '''rfvIncludebackend control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rfvIncludebackend As Global.System.Web.UI.WebControls.RequiredFieldValidator
    
    '''<summary>
    '''rblIncludebackend control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rblIncludebackend As Global.System.Web.UI.WebControls.RadioButtonList
    
    '''<summary>
    '''pnlBackend control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlBackend As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''rptTest control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rptTest As Global.System.Web.UI.WebControls.Repeater
    
    '''<summary>
    '''cvBackendPath control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cvBackendPath As Global.System.Web.UI.WebControls.CustomValidator
    
    '''<summary>
    '''pnlBackendFolder control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlBackendFolder As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''lblSelectedBackendFolder control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblSelectedBackendFolder As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lsbBackendFolders control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lsbBackendFolders As Global.System.Web.UI.WebControls.ListBox
    
    '''<summary>
    '''rfvCreateBackendFolder control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rfvCreateBackendFolder As Global.System.Web.UI.WebControls.RequiredFieldValidator
    
    '''<summary>
    '''rblCreateBackendFolder control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rblCreateBackendFolder As Global.System.Web.UI.WebControls.RadioButtonList
    
    '''<summary>
    '''pnlNewBackendFolder control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlNewBackendFolder As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''rfvNewBackendFolderName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rfvNewBackendFolderName As Global.System.Web.UI.WebControls.RequiredFieldValidator
    
    '''<summary>
    '''txtNewBackendFolderName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtNewBackendFolderName As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''rfvBackendLink control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rfvBackendLink As Global.System.Web.UI.WebControls.RequiredFieldValidator
    
    '''<summary>
    '''cvBackendLink control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cvBackendLink As Global.System.Web.UI.WebControls.CustomValidator
    
    '''<summary>
    '''txtBackendLink control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtBackendLink As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''lblSelectedDisplayColumns control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblSelectedDisplayColumns As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lsbDisplayColumns control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lsbDisplayColumns As Global.System.Web.UI.WebControls.ListBox
    
    '''<summary>
    '''cblBackendOptions control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cblBackendOptions As Global.System.Web.UI.WebControls.CheckBoxList
    
    '''<summary>
    '''pnlShowOptionDetails control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlShowOptionDetails As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''OptionTabs control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents OptionTabs As Global.AjaxControlToolkit.TabContainer
    
    '''<summary>
    '''Search control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Search As Global.AjaxControlToolkit.TabPanel
    
    '''<summary>
    '''rfvSearchColumns control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rfvSearchColumns As Global.System.Web.UI.WebControls.RequiredFieldValidator
    
    '''<summary>
    '''lblSearchColumns control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblSearchColumns As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''ddlSearchColumns control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlSearchColumns As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''lblSelectedSearchTermControls control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblSelectedSearchTermControls As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lsbSearchTermControls control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lsbSearchTermControls As Global.System.Web.UI.WebControls.ListBox
    
    '''<summary>
    '''lblSelectedSearchDisplayColumns control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblSelectedSearchDisplayColumns As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lsbSearchDisplayColumns control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lsbSearchDisplayColumns As Global.System.Web.UI.WebControls.ListBox
    
    '''<summary>
    '''rfvActions control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rfvActions As Global.System.Web.UI.WebControls.RequiredFieldValidator
    
    '''<summary>
    '''lblActions control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblActions As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''ddlActions control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlActions As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''rptActions control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rptActions As Global.System.Web.UI.WebControls.Repeater
    
    '''<summary>
    '''rblDefaultSort control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rblDefaultSort As Global.System.Web.UI.WebControls.RadioButtonList
    
    '''<summary>
    '''rfvSortColumns control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rfvSortColumns As Global.System.Web.UI.WebControls.RequiredFieldValidator
    
    '''<summary>
    '''ddlSortColumns control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlSortColumns As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''rptSortColumns control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rptSortColumns As Global.System.Web.UI.WebControls.Repeater
    
    '''<summary>
    '''rfvFilterOptions control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rfvFilterOptions As Global.System.Web.UI.WebControls.RequiredFieldValidator
    
    '''<summary>
    '''lblFilterOptions control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblFilterOptions As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''ddlFilterOptions control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlFilterOptions As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''rptFilterOptions control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rptFilterOptions As Global.System.Web.UI.WebControls.Repeater
    
    '''<summary>
    '''rfvNumberExports control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rfvNumberExports As Global.System.Web.UI.WebControls.RequiredFieldValidator
    
    '''<summary>
    '''lblNumberExports control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblNumberExports As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''ddlNumberExports control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlNumberExports As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''rptExports control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rptExports As Global.System.Web.UI.WebControls.Repeater
    
    '''<summary>
    '''rfvNumberReports control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rfvNumberReports As Global.System.Web.UI.WebControls.RequiredFieldValidator
    
    '''<summary>
    '''lblNumberReports control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblNumberReports As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''ddlNumberReports control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlNumberReports As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''rptReports control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rptReports As Global.System.Web.UI.WebControls.Repeater
    
    '''<summary>
    '''rfvName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rfvName As Global.System.Web.UI.WebControls.RequiredFieldValidator
    
    '''<summary>
    '''lblName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblName As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''txtName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtName As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''rfvType control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rfvType As Global.System.Web.UI.WebControls.RequiredFieldValidator
    
    '''<summary>
    '''rblDataSourceType control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rblDataSourceType As Global.System.Web.UI.WebControls.RadioButtonList
    
    '''<summary>
    '''ucDataSource control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ucDataSource As Global.stable.WebRADDataSource
    
    '''<summary>
    '''pnlStatement control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlStatement As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''rfvSQLQuery control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rfvSQLQuery As Global.System.Web.UI.WebControls.RequiredFieldValidator
    
    '''<summary>
    '''lblSQLQuery control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblSQLQuery As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''txtSQLQuery control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtSQLQuery As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''pnlColumns control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlColumns As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''cvMainColumns control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cvMainColumns As Global.System.Web.UI.WebControls.CustomValidator
    
    '''<summary>
    '''lblMainTableName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblMainTableName As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lsbMainColumns control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lsbMainColumns As Global.System.Web.UI.WebControls.ListBox
    
    '''<summary>
    '''rptTables control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rptTables As Global.System.Web.UI.WebControls.Repeater
    
    '''<summary>
    '''rblTemplateMessageType control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rblTemplateMessageType As Global.System.Web.UI.WebControls.RadioButtonList
    
    '''<summary>
    '''txtTemplate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtTemplate As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtTemplatePlain control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtTemplatePlain As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''lblFormName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblFormName As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''txtClosedMessage control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtClosedMessage As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''ucCustomSelectDataSource control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ucCustomSelectDataSource As Global.stable.WebRADDataSource
    
    '''<summary>
    '''cmpPageLimit control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmpPageLimit As Global.System.Web.UI.WebControls.CompareValidator
    
    '''<summary>
    '''rfvPageLimit control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rfvPageLimit As Global.System.Web.UI.WebControls.RequiredFieldValidator
    
    '''<summary>
    '''rvPageLimit control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rvPageLimit As Global.System.Web.UI.WebControls.RangeValidator
    
    '''<summary>
    '''lblPageLimit control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblPageLimit As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''txtPageLimit control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtPageLimit As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''rfvNumberAncillaryMaintenance control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rfvNumberAncillaryMaintenance As Global.System.Web.UI.WebControls.RequiredFieldValidator
    
    '''<summary>
    '''lblNumberAncillaryMaintenance control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblNumberAncillaryMaintenance As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''ddlNumberAncillaryMaintenance control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlNumberAncillaryMaintenance As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''rptAncillaryMaintenance control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rptAncillaryMaintenance As Global.System.Web.UI.WebControls.Repeater
    
    '''<summary>
    '''cvAdditionalLinks control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cvAdditionalLinks As Global.System.Web.UI.WebControls.CustomValidator
    
    '''<summary>
    '''rptAdditionalLinks control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rptAdditionalLinks As Global.System.Web.UI.WebControls.Repeater
    
    '''<summary>
    '''btnrptAdditionalLinksAddItem control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnrptAdditionalLinksAddItem As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''btnContinue control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnContinue As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''vsWebRAD control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents vsWebRAD As Global.System.Web.UI.WebControls.ValidationSummary
End Class
