'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class backend
    
    '''<summary>
    '''Form1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Form1 As Global.System.Web.UI.HtmlControls.HtmlForm
    
    '''<summary>
    '''scriptManager control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents scriptManager As Global.System.Web.UI.ScriptManager
    
    '''<summary>
    '''rfvIncludebackend control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rfvIncludebackend As Global.System.Web.UI.WebControls.RequiredFieldValidator
    
    '''<summary>
    '''rblIncludebackend control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rblIncludebackend As Global.System.Web.UI.WebControls.RadioButtonList
    
    '''<summary>
    '''pnlBackend control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlBackend As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''ddlTest control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlTest As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''rptTest control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rptTest As Global.System.Web.UI.WebControls.Repeater
    
    '''<summary>
    '''cvBackendPath control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cvBackendPath As Global.System.Web.UI.WebControls.CustomValidator
    
    '''<summary>
    '''pnlBackendFolder control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlBackendFolder As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''lblSelectedBackendFolder control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblSelectedBackendFolder As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lsbBackendFolders control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lsbBackendFolders As Global.System.Web.UI.WebControls.ListBox
    
    '''<summary>
    '''rfvCreateBackendFolder control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rfvCreateBackendFolder As Global.System.Web.UI.WebControls.RequiredFieldValidator
    
    '''<summary>
    '''rblCreateBackendFolder control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rblCreateBackendFolder As Global.System.Web.UI.WebControls.RadioButtonList
    
    '''<summary>
    '''pnlNewBackendFolder control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlNewBackendFolder As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''rfvNewBackendFolderName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rfvNewBackendFolderName As Global.System.Web.UI.WebControls.RequiredFieldValidator
    
    '''<summary>
    '''txtNewBackendFolderName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtNewBackendFolderName As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''rfvBackendLink control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rfvBackendLink As Global.System.Web.UI.WebControls.RequiredFieldValidator
    
    '''<summary>
    '''cvBackendLink control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cvBackendLink As Global.System.Web.UI.WebControls.CustomValidator
    
    '''<summary>
    '''txtBackendLink control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtBackendLink As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''lblSelectedDisplayColumns control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblSelectedDisplayColumns As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lsbDisplayColumns control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lsbDisplayColumns As Global.System.Web.UI.WebControls.ListBox
    
    '''<summary>
    '''cblBackendOptions control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cblBackendOptions As Global.System.Web.UI.WebControls.CheckBoxList
    
    '''<summary>
    '''pnlSearch control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlSearch As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''rfvSearchColumns control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rfvSearchColumns As Global.System.Web.UI.WebControls.RequiredFieldValidator
    
    '''<summary>
    '''ddlSearchColumns control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlSearchColumns As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''lblSelectedSearchTermControls control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblSelectedSearchTermControls As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lsbSearchTermControls control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lsbSearchTermControls As Global.System.Web.UI.WebControls.ListBox
    
    '''<summary>
    '''lblSelectedSearchDisplayColumns control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblSelectedSearchDisplayColumns As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lsbSearchDisplayColumns control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lsbSearchDisplayColumns As Global.System.Web.UI.WebControls.ListBox
    
    '''<summary>
    '''pnlActionsOtherThanDelete control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlActionsOtherThanDelete As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''rfvActions control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rfvActions As Global.System.Web.UI.WebControls.RequiredFieldValidator
    
    '''<summary>
    '''ddlActions control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlActions As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''rptActions control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rptActions As Global.System.Web.UI.WebControls.Repeater
    
    '''<summary>
    '''pnlSort control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlSort As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''rblDefaultSort control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rblDefaultSort As Global.System.Web.UI.WebControls.RadioButtonList
    
    '''<summary>
    '''rfvSortColumns control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rfvSortColumns As Global.System.Web.UI.WebControls.RequiredFieldValidator
    
    '''<summary>
    '''ddlSortColumns control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlSortColumns As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''rptSortColumns control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rptSortColumns As Global.System.Web.UI.WebControls.Repeater
    
    '''<summary>
    '''pnlFilter control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlFilter As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''rfvFilterOptions control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rfvFilterOptions As Global.System.Web.UI.WebControls.RequiredFieldValidator
    
    '''<summary>
    '''ddlFilterOptions control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlFilterOptions As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''rptFilterOptions control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rptFilterOptions As Global.System.Web.UI.WebControls.Repeater
    
    '''<summary>
    '''pnlExport control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlExport As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''rfvNumberExports control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rfvNumberExports As Global.System.Web.UI.WebControls.RequiredFieldValidator
    
    '''<summary>
    '''ddlNumberExports control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlNumberExports As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''rptExports control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rptExports As Global.System.Web.UI.WebControls.Repeater
    
    '''<summary>
    '''pnlReport control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlReport As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''rfvNumberReports control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rfvNumberReports As Global.System.Web.UI.WebControls.RequiredFieldValidator
    
    '''<summary>
    '''ddlNumberReports control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlNumberReports As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''rptReports control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rptReports As Global.System.Web.UI.WebControls.Repeater
    
    '''<summary>
    '''pnlSchedulePage control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlSchedulePage As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''lblFormName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblFormName As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''txtClosedMessage control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtClosedMessage As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''pnlCustomselectstatement control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlCustomselectstatement As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''rfvCustomSelectStatement control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rfvCustomSelectStatement As Global.System.Web.UI.WebControls.RequiredFieldValidator
    
    '''<summary>
    '''txtCustomSelectStatement control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtCustomSelectStatement As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''pnlPaging control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlPaging As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''cmpPageLimit control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmpPageLimit As Global.System.Web.UI.WebControls.CompareValidator
    
    '''<summary>
    '''rfvPageLimit control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rfvPageLimit As Global.System.Web.UI.WebControls.RequiredFieldValidator
    
    '''<summary>
    '''rvPageLimit control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rvPageLimit As Global.System.Web.UI.WebControls.RangeValidator
    
    '''<summary>
    '''txtPageLimit control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtPageLimit As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''pnlAncillarymaintenance control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlAncillarymaintenance As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''rfvNumberAncillaryMaintenance control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rfvNumberAncillaryMaintenance As Global.System.Web.UI.WebControls.RequiredFieldValidator
    
    '''<summary>
    '''ddlNumberAncillaryMaintenance control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlNumberAncillaryMaintenance As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''rptAncillaryMaintenance control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rptAncillaryMaintenance As Global.System.Web.UI.WebControls.Repeater
    
    '''<summary>
    '''pnlAdditionalLinks control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlAdditionalLinks As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''cvAdditionalLinks control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cvAdditionalLinks As Global.System.Web.UI.WebControls.CustomValidator
    
    '''<summary>
    '''rptAdditionalLinks control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rptAdditionalLinks As Global.System.Web.UI.WebControls.Repeater
    
    '''<summary>
    '''btnrptAdditionalLinksAddItem control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnrptAdditionalLinksAddItem As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''btnContinue control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnContinue As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''vsWebRAD control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents vsWebRAD As Global.System.Web.UI.WebControls.ValidationSummary
End Class
