'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class controlsnew
    
    '''<summary>
    '''ddlParentControls control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlParentControls As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''btnSetParent control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnSetParent As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''txtSetGroupName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtSetGroupName As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''btnSetGroup control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnSetGroup As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''btnDeleteControls control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnDeleteControls As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''MainContent_btnAlignControls control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents MainContent_btnAlignControls As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''rptPages control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rptPages As Global.System.Web.UI.WebControls.Repeater
    
    '''<summary>
    '''imbAddPage control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents imbAddPage As Global.System.Web.UI.WebControls.ImageButton
    
    '''<summary>
    '''sds control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents sds As Global.System.Web.UI.WebControls.SqlDataSource
    
    '''<summary>
    '''chkSelectAllControls control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkSelectAllControls As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''lblSelectAllControls control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblSelectAllControls As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''rl1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rl1 As Global.AjaxControlToolkit.ReorderList
    
    '''<summary>
    '''vs2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents vs2 As Global.System.Web.UI.WebControls.ValidationSummary
    
    '''<summary>
    '''btnContinue2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnContinue2 As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''rfvControlType control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rfvControlType As Global.System.Web.UI.WebControls.RequiredFieldValidator
    
    '''<summary>
    '''lblControlType control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblControlType As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''ddlControlType control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlControlType As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''pnlParentControl control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlParentControl As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''lblParentControl control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblParentControl As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''ddlParentControl control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlParentControl As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''pnlControlTypeDetails control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlControlTypeDetails As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''rfvName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rfvName As Global.System.Web.UI.WebControls.RequiredFieldValidator
    
    '''<summary>
    '''cvName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cvName As Global.System.Web.UI.WebControls.CustomValidator
    
    '''<summary>
    '''lblName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblName As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''txtName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtName As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''pnlDisplayHeading control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlDisplayHeading As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''rfvDisplayHeading control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rfvDisplayHeading As Global.System.Web.UI.WebControls.RequiredFieldValidator
    
    '''<summary>
    '''lblDisplayHeading control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblDisplayHeading As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''rblDisplayHeading control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rblDisplayHeading As Global.System.Web.UI.WebControls.RadioButtonList
    
    '''<summary>
    '''pnlHeading control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlHeading As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''rfvHeading control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rfvHeading As Global.System.Web.UI.WebControls.RequiredFieldValidator
    
    '''<summary>
    '''lblHeading control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblHeading As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''txtHeading control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtHeading As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''pnlSubheading control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlSubheading As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''lblSubHeading control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblSubHeading As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''txtSubHeading control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtSubHeading As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''pnlShortHeading control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlShortHeading As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''rfvShortHeading control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rfvShortHeading As Global.System.Web.UI.WebControls.RequiredFieldValidator
    
    '''<summary>
    '''lblShortHeading control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblShortHeading As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''txtShortHeading control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtShortHeading As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''pnlRepeaterAddRemove control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlRepeaterAddRemove As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''lblRepeaterAddRemove control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblRepeaterAddRemove As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''rblRepeaterAddRemove control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rblRepeaterAddRemove As Global.System.Web.UI.WebControls.RadioButtonList
    
    '''<summary>
    '''pnlRepeaterItemName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlRepeaterItemName As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''rfvRepeaterItemName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rfvRepeaterItemName As Global.System.Web.UI.WebControls.RequiredFieldValidator
    
    '''<summary>
    '''lblRepeaterItemName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblRepeaterItemName As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''txtRepeaterItemName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtRepeaterItemName As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''pnlRequired control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlRequired As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''rfvRequired control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rfvRequired As Global.System.Web.UI.WebControls.RequiredFieldValidator
    
    '''<summary>
    '''lblRequired control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblRequired As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''rblRequired control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rblRequired As Global.System.Web.UI.WebControls.RadioButtonList
    
    '''<summary>
    '''pnlMinimumRequired control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlMinimumRequired As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''rfvMinimumRequired control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rfvMinimumRequired As Global.System.Web.UI.WebControls.RequiredFieldValidator
    
    '''<summary>
    '''lblMinimumRequired control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblMinimumRequired As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''ddlMinimumRequired control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlMinimumRequired As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''lblMaximumRequired control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblMaximumRequired As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''ddlMaximumRequired control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlMaximumRequired As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''pnlCustomValidation control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlCustomValidation As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''rfvCustomValidation control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rfvCustomValidation As Global.System.Web.UI.WebControls.RequiredFieldValidator
    
    '''<summary>
    '''lblCustomValidation control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblCustomValidation As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''rblCustomValidation control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rblCustomValidation As Global.System.Web.UI.WebControls.RadioButtonList
    
    '''<summary>
    '''pnlCustomValidationCode control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlCustomValidationCode As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''cvCustomValidationCode control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cvCustomValidationCode As Global.System.Web.UI.WebControls.CustomValidator
    
    '''<summary>
    '''lblCustomValidationCode control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblCustomValidationCode As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''txtCustomValidationCode control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtCustomValidationCode As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''pnlRequireVerification control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlRequireVerification As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''rfvRequireVerification control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rfvRequireVerification As Global.System.Web.UI.WebControls.RequiredFieldValidator
    
    '''<summary>
    '''lblRequireVerification control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblRequireVerification As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''rblRequireVerification control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rblRequireVerification As Global.System.Web.UI.WebControls.RadioButtonList
    
    '''<summary>
    '''pnlTextPosition control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlTextPosition As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''rfvTextPosition control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rfvTextPosition As Global.System.Web.UI.WebControls.RequiredFieldValidator
    
    '''<summary>
    '''lblTextPosition control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblTextPosition As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''rblTextPosition control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rblTextPosition As Global.System.Web.UI.WebControls.RadioButtonList
    
    '''<summary>
    '''pnlLayoutType control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlLayoutType As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''rfvLayoutType control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rfvLayoutType As Global.System.Web.UI.WebControls.RequiredFieldValidator
    
    '''<summary>
    '''lblLayoutType control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblLayoutType As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''rblLayoutType control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rblLayoutType As Global.System.Web.UI.WebControls.RadioButtonList
    
    '''<summary>
    '''rfvLayoutSubtype control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rfvLayoutSubtype As Global.System.Web.UI.WebControls.RequiredFieldValidator
    
    '''<summary>
    '''lblLayoutSubtype control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblLayoutSubtype As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''rblLayoutSubtype control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rblLayoutSubtype As Global.System.Web.UI.WebControls.RadioButtonList
    
    '''<summary>
    '''pnlSupplyControlData control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlSupplyControlData As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''rfvSupplyControlData control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rfvSupplyControlData As Global.System.Web.UI.WebControls.RequiredFieldValidator
    
    '''<summary>
    '''lblSupplyControlData control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblSupplyControlData As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''rblSupplyControlData control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rblSupplyControlData As Global.System.Web.UI.WebControls.RadioButtonList
    
    '''<summary>
    '''pnlSupplyDataType control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlSupplyDataType As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''lblSupplyDataType control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblSupplyDataType As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''rblSupplyDataType control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rblSupplyDataType As Global.System.Web.UI.WebControls.RadioButtonList
    
    '''<summary>
    '''pnlControlDataSource control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlControlDataSource As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''lblontrolSupplyDataSource control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblontrolSupplyDataSource As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''pnlControlDataSourceColumn control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlControlDataSourceColumn As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''rfvControlDataSourceColumn control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rfvControlDataSourceColumn As Global.System.Web.UI.WebControls.RequiredFieldValidator
    
    '''<summary>
    '''lblControlDataSourceColumn control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblControlDataSourceColumn As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''txtControlDataSourceColumn control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtControlDataSourceColumn As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''rfvDisplayLocation control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rfvDisplayLocation As Global.System.Web.UI.WebControls.RequiredFieldValidator
    
    '''<summary>
    '''lblDisplayLocation control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblDisplayLocation As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''rblDisplayLocation control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rblDisplayLocation As Global.System.Web.UI.WebControls.RadioButtonList
    
    '''<summary>
    '''rfvDisplayType control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rfvDisplayType As Global.System.Web.UI.WebControls.RequiredFieldValidator
    
    '''<summary>
    '''lblDisplayType control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblDisplayType As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''ddlDisplayType control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlDisplayType As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''pnlIncludeDatabase control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlIncludeDatabase As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''rfvIncludeDatabase control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rfvIncludeDatabase As Global.System.Web.UI.WebControls.RequiredFieldValidator
    
    '''<summary>
    '''lblIncludeDatabase control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblIncludeDatabase As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''rblIncludeDatabase control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rblIncludeDatabase As Global.System.Web.UI.WebControls.RadioButtonList
    
    '''<summary>
    '''pnlAutopostback control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlAutopostback As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''rfvAutopostback control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rfvAutopostback As Global.System.Web.UI.WebControls.RequiredFieldValidator
    
    '''<summary>
    '''lblAutopostback control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblAutopostback As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''rblAutopostback control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rblAutopostback As Global.System.Web.UI.WebControls.RadioButtonList
    
    '''<summary>
    '''pnlPostbackActionOptions control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlPostbackActionOptions As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''pnlPerformPostbackAction control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlPerformPostbackAction As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''rfvPerformPostbackAction control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rfvPerformPostbackAction As Global.System.Web.UI.WebControls.RequiredFieldValidator
    
    '''<summary>
    '''lblPerformPostbackAction control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblPerformPostbackAction As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''rblPerformPostbackAction control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rblPerformPostbackAction As Global.System.Web.UI.WebControls.RadioButtonList
    
    '''<summary>
    '''pnlPostbackActions control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlPostbackActions As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''rfvPostbackActions control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rfvPostbackActions As Global.System.Web.UI.WebControls.RequiredFieldValidator
    
    '''<summary>
    '''lblActions control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblActions As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''ddlActions control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlActions As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''rptPostbackActions control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rptPostbackActions As Global.System.Web.UI.WebControls.Repeater
    
    '''<summary>
    '''pnlOnchange control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlOnchange As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''lblOnchange control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblOnchange As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''rblOnchange control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rblOnchange As Global.System.Web.UI.WebControls.RadioButtonList
    
    '''<summary>
    '''pnlOnchangeDetail control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlOnchangeDetail As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''rfvOnchangeCall control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rfvOnchangeCall As Global.System.Web.UI.WebControls.RequiredFieldValidator
    
    '''<summary>
    '''lblOnchangeCall control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblOnchangeCall As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''txtOnchangeCall control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtOnchangeCall As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''lblOnchangeBody control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblOnchangeBody As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''txtOnchangeBody control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtOnchangeBody As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''pnlEnabled control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlEnabled As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''lblEnabled control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblEnabled As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''rblEnabled control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rblEnabled As Global.System.Web.UI.WebControls.RadioButtonList
    
    '''<summary>
    '''pnlVisible control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlVisible As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''rfvVisible control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rfvVisible As Global.System.Web.UI.WebControls.RequiredFieldValidator
    
    '''<summary>
    '''lblVisible control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblVisible As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''rblVisible control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rblVisible As Global.System.Web.UI.WebControls.RadioButtonList
    
    '''<summary>
    '''pnlDependentValue control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlDependentValue As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''cvVisibleDependingControls control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cvVisibleDependingControls As Global.System.Web.UI.WebControls.CustomValidator
    
    '''<summary>
    '''rptVisibleDependingControls control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rptVisibleDependingControls As Global.System.Web.UI.WebControls.Repeater
    
    '''<summary>
    '''btnrptVisibleDependingControlsAddItem control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnrptVisibleDependingControlsAddItem As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''pnlCustomVisibleValue control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlCustomVisibleValue As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''rfvCustomVisibleValue control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rfvCustomVisibleValue As Global.System.Web.UI.WebControls.RequiredFieldValidator
    
    '''<summary>
    '''lblCustomVisibleValue control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblCustomVisibleValue As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''txtCustomVisibleValue control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtCustomVisibleValue As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''pnlCalendar control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlCalendar As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''rfvCalendar control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rfvCalendar As Global.System.Web.UI.WebControls.RequiredFieldValidator
    
    '''<summary>
    '''lblCalendar control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblCalendar As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''rblCalendar control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rblCalendar As Global.System.Web.UI.WebControls.RadioButtonList
    
    '''<summary>
    '''pnlValue control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlValue As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''rfvRichtextbox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rfvRichtextbox As Global.System.Web.UI.WebControls.RequiredFieldValidator
    
    '''<summary>
    '''lblRichTextbox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblRichTextbox As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''rblRichTextbox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rblRichTextbox As Global.System.Web.UI.WebControls.RadioButtonList
    
    '''<summary>
    '''pnlRegularValue control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlRegularValue As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''rfvValue control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rfvValue As Global.System.Web.UI.WebControls.RequiredFieldValidator
    
    '''<summary>
    '''txtValue control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtValue As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''pnlRichValue control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlRichValue As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''rfvRichValue control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rfvRichValue As Global.System.Web.UI.WebControls.RequiredFieldValidator
    
    '''<summary>
    '''txtRichValue control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtRichValue As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''pnlText control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlText As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''rfvText control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rfvText As Global.System.Web.UI.WebControls.RequiredFieldValidator
    
    '''<summary>
    '''lblText control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblText As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''txtText control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtText As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''pnlPlaceholder control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlPlaceholder As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''lblPlaceholder control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblPlaceholder As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''txtPlaceholder control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtPlaceholder As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''pnlTextMode control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlTextMode As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''lblTextMode control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblTextMode As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''ddlTextMode control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlTextMode As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''pnlRichTextboxUser control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlRichTextboxUser As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''rfvRichTextboxUser control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rfvRichTextboxUser As Global.System.Web.UI.WebControls.RequiredFieldValidator
    
    '''<summary>
    '''lblRichTextboxUser control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblRichTextboxUser As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''rblRichTextboxUser control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rblRichTextboxUser As Global.System.Web.UI.WebControls.RadioButtonList
    
    '''<summary>
    '''pnlRows control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlRows As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''rfvRows control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rfvRows As Global.System.Web.UI.WebControls.RequiredFieldValidator
    
    '''<summary>
    '''cmpRows control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmpRows As Global.System.Web.UI.WebControls.CompareValidator
    
    '''<summary>
    '''lblRows control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblRows As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''txtRows control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtRows As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''pnlColumns control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlColumns As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''rfvColumns control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rfvColumns As Global.System.Web.UI.WebControls.RequiredFieldValidator
    
    '''<summary>
    '''cmpColumns control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmpColumns As Global.System.Web.UI.WebControls.CompareValidator
    
    '''<summary>
    '''lblColumns control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblColumns As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''txtColumns control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtColumns As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''pnlMaxLength control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlMaxLength As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''rfvMaxLength control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rfvMaxLength As Global.System.Web.UI.WebControls.RequiredFieldValidator
    
    '''<summary>
    '''cmpMaxLength control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmpMaxLength As Global.System.Web.UI.WebControls.CompareValidator
    
    '''<summary>
    '''lblMaxLength control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblMaxLength As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''txtMaxLength control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtMaxLength As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''lblMaxLengthType control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblMaxLengthType As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''rblMaxLengthType control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rblMaxLengthType As Global.System.Web.UI.WebControls.RadioButtonList
    
    '''<summary>
    '''pnlMaxFileSize control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlMaxFileSize As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''rfvMaxFileSize control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rfvMaxFileSize As Global.System.Web.UI.WebControls.RequiredFieldValidator
    
    '''<summary>
    '''cmpMaxFileSize control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmpMaxFileSize As Global.System.Web.UI.WebControls.CompareValidator
    
    '''<summary>
    '''lblMaxFileSize control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblMaxFileSize As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''txtMaxFileSize control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtMaxFileSize As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''pnlFileTypesAllowed control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlFileTypesAllowed As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''cvFileTypesAllowed control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cvFileTypesAllowed As Global.System.Web.UI.WebControls.CustomValidator
    
    '''<summary>
    '''lblFileTypesAllowed control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblFileTypesAllowed As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lsbFileTypesAllowed control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lsbFileTypesAllowed As Global.System.Web.UI.WebControls.ListBox
    
    '''<summary>
    '''pnlUploadPath control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlUploadPath As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''cvUploadPath control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cvUploadPath As Global.System.Web.UI.WebControls.CustomValidator
    
    '''<summary>
    '''lblUploadPathFolder control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblUploadPathFolder As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''pnlUploadPathFolder control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlUploadPathFolder As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''lblSelectedUploadPathFolder control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblSelectedUploadPathFolder As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lsbUploadPathFolders control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lsbUploadPathFolders As Global.System.Web.UI.WebControls.ListBox
    
    '''<summary>
    '''rfvCreateUploadPathFolder control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rfvCreateUploadPathFolder As Global.System.Web.UI.WebControls.RequiredFieldValidator
    
    '''<summary>
    '''lblCreateUploadPathFolder control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblCreateUploadPathFolder As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''rblCreateUploadPathFolder control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rblCreateUploadPathFolder As Global.System.Web.UI.WebControls.RadioButtonList
    
    '''<summary>
    '''pnlNewUploadPathFolder control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlNewUploadPathFolder As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''rfvNewUploadPathFolderName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rfvNewUploadPathFolderName As Global.System.Web.UI.WebControls.RequiredFieldValidator
    
    '''<summary>
    '''lblNewUploadPathFolderName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblNewUploadPathFolderName As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''txtNewUploadPathFolderName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtNewUploadPathFolderName As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''pnlWidth control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlWidth As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''rfvWidth control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rfvWidth As Global.System.Web.UI.WebControls.RequiredFieldValidator
    
    '''<summary>
    '''lblWidth control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblWidth As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''txtWidth control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtWidth As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''pnlCssClass control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlCssClass As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''rfvCssClass control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rfvCssClass As Global.System.Web.UI.WebControls.RequiredFieldValidator
    
    '''<summary>
    '''lblCssClass control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblCssClass As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''txtCssClass control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtCssClass As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''pnlRepeatDirection control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlRepeatDirection As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''rfvRepeatDirection control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rfvRepeatDirection As Global.System.Web.UI.WebControls.RequiredFieldValidator
    
    '''<summary>
    '''lblRepeatDirection control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblRepeatDirection As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''rblRepeatDirection control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rblRepeatDirection As Global.System.Web.UI.WebControls.RadioButtonList
    
    '''<summary>
    '''pnlRepeatColumns control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlRepeatColumns As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''rfvRepeatColumns control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rfvRepeatColumns As Global.System.Web.UI.WebControls.RequiredFieldValidator
    
    '''<summary>
    '''lblRepeatColumns control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblRepeatColumns As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''ddlRepeatColumns control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlRepeatColumns As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''pnlListSelections control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlListSelections As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''rfvListSelections control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rfvListSelections As Global.System.Web.UI.WebControls.RequiredFieldValidator
    
    '''<summary>
    '''lblListSelections control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblListSelections As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''rblListSelections control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rblListSelections As Global.System.Web.UI.WebControls.RadioButtonList
    
    '''<summary>
    '''pnlGroupName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlGroupName As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''rfvGroupName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rfvGroupName As Global.System.Web.UI.WebControls.RequiredFieldValidator
    
    '''<summary>
    '''lblGroupName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblGroupName As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''txtGroupName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtGroupName As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''pnlSelectionMode control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlSelectionMode As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''rfvSelectionMode control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rfvSelectionMode As Global.System.Web.UI.WebControls.RequiredFieldValidator
    
    '''<summary>
    '''lblSelectionMode control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblSelectionMode As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''rblSelectionMode control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rblSelectionMode As Global.System.Web.UI.WebControls.RadioButtonList
    
    '''<summary>
    '''pnlSQLDataType control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlSQLDataType As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''rfvSQLDataType control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rfvSQLDataType As Global.System.Web.UI.WebControls.RequiredFieldValidator
    
    '''<summary>
    '''lblSQLDataType control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblSQLDataType As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''ddlSQLDataType control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlSQLDataType As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''pnlSQLDataSize control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlSQLDataSize As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''rfvSQLDataSize control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rfvSQLDataSize As Global.System.Web.UI.WebControls.RequiredFieldValidator
    
    '''<summary>
    '''cvSQLDataSize control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cvSQLDataSize As Global.System.Web.UI.WebControls.CustomValidator
    
    '''<summary>
    '''lblSQLDataSize control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblSQLDataSize As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''txtSQLDataSize control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtSQLDataSize As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''pnlSQLDefaultValue control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlSQLDefaultValue As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''rfvSQLDefaultValueType control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rfvSQLDefaultValueType As Global.System.Web.UI.WebControls.RequiredFieldValidator
    
    '''<summary>
    '''rblSQLDefaultValueType control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rblSQLDefaultValueType As Global.System.Web.UI.WebControls.RadioButtonList
    
    '''<summary>
    '''rfvSQLDefaultValue control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rfvSQLDefaultValue As Global.System.Web.UI.WebControls.RequiredFieldValidator
    
    '''<summary>
    '''lblSQLDefaultValue control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblSQLDefaultValue As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''txtSQLDefaultValue control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtSQLDefaultValue As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''pnlAllowNegativeValue control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlAllowNegativeValue As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''lblAllowNegativeValue control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblAllowNegativeValue As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''rblAllowNegativeValue control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rblAllowNegativeValue As Global.System.Web.UI.WebControls.RadioButtonList
    
    '''<summary>
    '''pnlAllowZeroValue control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlAllowZeroValue As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''lblAllowZeroValue control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblAllowZeroValue As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''rblAllowZeroValue control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rblAllowZeroValue As Global.System.Web.UI.WebControls.RadioButtonList
    
    '''<summary>
    '''pnlSQLInsertItemTable control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlSQLInsertItemTable As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''rfvSQLInsertItemTable control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rfvSQLInsertItemTable As Global.System.Web.UI.WebControls.RequiredFieldValidator
    
    '''<summary>
    '''lblSQLInsertItemTable control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblSQLInsertItemTable As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''txtSQLInsertItemTable control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtSQLInsertItemTable As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''pnlSQLInsertItemStoredProcedure control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlSQLInsertItemStoredProcedure As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''rfvSQLInsertItemStoredProcedure control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rfvSQLInsertItemStoredProcedure As Global.System.Web.UI.WebControls.RequiredFieldValidator
    
    '''<summary>
    '''lblSQLInsertItemStoredProcedure control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblSQLInsertItemStoredProcedure As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''txtSQLInsertItemStoredProcedure control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtSQLInsertItemStoredProcedure As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''pnlForeignID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlForeignID As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''rfvForeignID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rfvForeignID As Global.System.Web.UI.WebControls.RequiredFieldValidator
    
    '''<summary>
    '''lblForeignID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblForeignID As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''txtForeignID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtForeignID As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''pnlProspectCode control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlProspectCode As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''rfvProspectCode control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rfvProspectCode As Global.System.Web.UI.WebControls.RequiredFieldValidator
    
    '''<summary>
    '''lblProspectCode control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblProspectCode As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''txtProspectCode control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtProspectCode As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''lblCurrentControlID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblCurrentControlID As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblCurrentControlPosition control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblCurrentControlPosition As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''btnContinue control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnContinue As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''vsWebRAD control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents vsWebRAD As Global.System.Web.UI.WebControls.ValidationSummary
End Class
