'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class WebRADDataSource
    
    '''<summary>
    '''pnlDataSourceType control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlDataSourceType As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''RequiredFieldValidator1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RequiredFieldValidator1 As Global.System.Web.UI.WebControls.RequiredFieldValidator
    
    '''<summary>
    '''rblDataSourceType control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rblDataSourceType As Global.System.Web.UI.WebControls.RadioButtonList
    
    '''<summary>
    '''pnlDataSource control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlDataSource As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''rfvDataSource control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rfvDataSource As Global.System.Web.UI.WebControls.RequiredFieldValidator
    
    '''<summary>
    '''lblDataSource control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblDataSource As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''txtDataSource control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtDataSource As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''chkUseBackendDatasource control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkUseBackendDatasource As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''pnlBackendDAtasource control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlBackendDAtasource As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''rfvBackendDatasource control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rfvBackendDatasource As Global.System.Web.UI.WebControls.RequiredFieldValidator
    
    '''<summary>
    '''lblBackendDatasource control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblBackendDatasource As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''txtBackendDatasource control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtBackendDatasource As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''pnlDataSourceSpecific control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlDataSourceSpecific As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''rfvDataSourceSelect control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rfvDataSourceSelect As Global.System.Web.UI.WebControls.RequiredFieldValidator
    
    '''<summary>
    '''lblDataSourceSelectHeader control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblDataSourceSelectHeader As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''txtDataSourceSelect control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtDataSourceSelect As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''lblDataSourceTableHeader control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblDataSourceTableHeader As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''txtDataSourceTable control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtDataSourceTable As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''lblDataSourceWhereHeader control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblDataSourceWhereHeader As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''txtDataSourceWhere control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtDataSourceWhere As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''lblDataSourceGroupByHeader control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblDataSourceGroupByHeader As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''txtDataSourceGroupBy control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtDataSourceGroupBy As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''lblDataSourceOrderByHeader control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblDataSourceOrderByHeader As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''txtDataSourceOrderBy control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtDataSourceOrderBy As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''pnlDataTextField control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlDataTextField As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''rfvDataTextField control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rfvDataTextField As Global.System.Web.UI.WebControls.RequiredFieldValidator
    
    '''<summary>
    '''lblDataTextFieldHeader control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblDataTextFieldHeader As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''txtDataTextField control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtDataTextField As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''pnlDataValueField control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlDataValueField As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''rfvDataValueField control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rfvDataValueField As Global.System.Web.UI.WebControls.RequiredFieldValidator
    
    '''<summary>
    '''lblDataValueFieldHeader control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblDataValueFieldHeader As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''txtDataValueField control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtDataValueField As Global.System.Web.UI.WebControls.TextBox
End Class
