'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class frontend
    
    '''<summary>
    '''Form1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Form1 As Global.System.Web.UI.HtmlControls.HtmlForm
    
    '''<summary>
    '''scriptManager control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents scriptManager As Global.System.Web.UI.ScriptManager
    
    '''<summary>
    '''rfvIncludeFrontend control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rfvIncludeFrontend As Global.System.Web.UI.WebControls.RequiredFieldValidator
    
    '''<summary>
    '''rblIncludeFrontend control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rblIncludeFrontend As Global.System.Web.UI.WebControls.RadioButtonList
    
    '''<summary>
    '''pnlFrontend control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlFrontend As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''cvFrontendPath control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cvFrontendPath As Global.System.Web.UI.WebControls.CustomValidator
    
    '''<summary>
    '''pnlFrontendFolder control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlFrontendFolder As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''lblSelectedFrontendFolder control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblSelectedFrontendFolder As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lsbFrontendFolders control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lsbFrontendFolders As Global.System.Web.UI.WebControls.ListBox
    
    '''<summary>
    '''rfvCreateFrontendFolder control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rfvCreateFrontendFolder As Global.System.Web.UI.WebControls.RequiredFieldValidator
    
    '''<summary>
    '''rblCreateFrontendFolder control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rblCreateFrontendFolder As Global.System.Web.UI.WebControls.RadioButtonList
    
    '''<summary>
    '''pnlNewFrontendFolder control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlNewFrontendFolder As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''rfvNewFrontendFolderName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rfvNewFrontendFolderName As Global.System.Web.UI.WebControls.RequiredFieldValidator
    
    '''<summary>
    '''txtNewFrontendFolderName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtNewFrontendFolderName As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''rfvFrontendLink control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rfvFrontendLink As Global.System.Web.UI.WebControls.RequiredFieldValidator
    
    '''<summary>
    '''cvFrontendLink control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cvFrontendLink As Global.System.Web.UI.WebControls.CustomValidator
    
    '''<summary>
    '''txtFrontendLink control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtFrontendLink As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''rfvRequireLogin control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rfvRequireLogin As Global.System.Web.UI.WebControls.RequiredFieldValidator
    
    '''<summary>
    '''rblRequireLogin control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rblRequireLogin As Global.System.Web.UI.WebControls.RadioButtonList
    
    '''<summary>
    '''pnlLoginColumns control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlLoginColumns As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''lsbLoginColumns control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lsbLoginColumns As Global.System.Web.UI.WebControls.ListBox
    
    '''<summary>
    '''rfvEmailSubmitter control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rfvEmailSubmitter As Global.System.Web.UI.WebControls.RequiredFieldValidator
    
    '''<summary>
    '''rblEmailSubmitter control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rblEmailSubmitter As Global.System.Web.UI.WebControls.RadioButtonList
    
    '''<summary>
    '''pnlEmailSubmitter control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlEmailSubmitter As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''rptEmailRecipients control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rptEmailRecipients As Global.System.Web.UI.WebControls.Repeater
    
    '''<summary>
    '''btnAddEmail control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnAddEmail As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''cblAdditionalOperationTypes control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cblAdditionalOperationTypes As Global.System.Web.UI.WebControls.CheckBoxList
    
    '''<summary>
    '''rptAdditionalOperationPages control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rptAdditionalOperationPages As Global.System.Web.UI.WebControls.Repeater
    
    '''<summary>
    '''cvSupervisor control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cvSupervisor As Global.System.Web.UI.WebControls.CustomValidator
    
    '''<summary>
    '''rptSupervisors control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rptSupervisors As Global.System.Web.UI.WebControls.Repeater
    
    '''<summary>
    '''txtSupervisorPLID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtSupervisorPLID As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''btnAdd control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnAdd As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''rfvEmailSupervisor control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rfvEmailSupervisor As Global.System.Web.UI.WebControls.RequiredFieldValidator
    
    '''<summary>
    '''rblEmailSupervisor control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rblEmailSupervisor As Global.System.Web.UI.WebControls.RadioButtonList
    
    '''<summary>
    '''pnlPages control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlPages As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''rfvMultipleSubmissions control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rfvMultipleSubmissions As Global.System.Web.UI.WebControls.RequiredFieldValidator
    
    '''<summary>
    '''rblMultipleSubmissions control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rblMultipleSubmissions As Global.System.Web.UI.WebControls.RadioButtonList
    
    '''<summary>
    '''pnlRetainedColumns control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlRetainedColumns As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''lblMainTableName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblMainTableName As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lsbMainColumns control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lsbMainColumns As Global.System.Web.UI.WebControls.ListBox
    
    '''<summary>
    '''rptTables control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rptTables As Global.System.Web.UI.WebControls.Repeater
    
    '''<summary>
    '''rptPages control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rptPages As Global.System.Web.UI.WebControls.Repeater
    
    '''<summary>
    '''pnlConfirmationPageMessage control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlConfirmationPageMessage As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''rblConfirmationPageMessageType control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rblConfirmationPageMessageType As Global.System.Web.UI.WebControls.RadioButtonList
    
    '''<summary>
    '''pnlConfirmationMessageRich control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlConfirmationMessageRich As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''txtConfirmationPageMessageRich control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtConfirmationPageMessageRich As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''pnlConfirmationMessagePlain control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlConfirmationMessagePlain As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''txtConfirmationPageMessagePlain control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtConfirmationPageMessagePlain As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''btnContinue control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnContinue As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''vsWebRAD control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents vsWebRAD As Global.System.Web.UI.WebControls.ValidationSummary
End Class
