'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class frontendnewpagetest

    '''<summary>
    '''rfvIncludeFrontend control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rfvIncludeFrontend As Global.System.Web.UI.WebControls.RequiredFieldValidator

    '''<summary>
    '''rblIncludeFrontend control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rblIncludeFrontend As Global.System.Web.UI.WebControls.RadioButtonList

    '''<summary>
    '''pnlFrontend control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlFrontend As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''updMain control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents updMain As Global.System.Web.UI.UpdatePanel

    '''<summary>
    '''cvFrontendPath control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cvFrontendPath As Global.System.Web.UI.WebControls.CustomValidator

    '''<summary>
    '''pnlFrontendFolder control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlFrontendFolder As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''lblSelectedFrontendFolder control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblSelectedFrontendFolder As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lsbFrontendFolders control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lsbFrontendFolders As Global.System.Web.UI.WebControls.ListBox

    '''<summary>
    '''rfvCreateFrontendFolder control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rfvCreateFrontendFolder As Global.System.Web.UI.WebControls.RequiredFieldValidator

    '''<summary>
    '''rblCreateFrontendFolder control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rblCreateFrontendFolder As Global.System.Web.UI.WebControls.RadioButtonList

    '''<summary>
    '''pnlNewFrontendFolder control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlNewFrontendFolder As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''rfvNewFrontendFolderName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rfvNewFrontendFolderName As Global.System.Web.UI.WebControls.RequiredFieldValidator

    '''<summary>
    '''txtNewFrontendFolderName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtNewFrontendFolderName As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''rfvFrontendLink control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rfvFrontendLink As Global.System.Web.UI.WebControls.RequiredFieldValidator

    '''<summary>
    '''cvFrontendLink control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cvFrontendLink As Global.System.Web.UI.WebControls.CustomValidator

    '''<summary>
    '''txtFrontendLink control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtFrontendLink As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''rfvRequireLogin control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rfvRequireLogin As Global.System.Web.UI.WebControls.RequiredFieldValidator

    '''<summary>
    '''rblRequireLogin control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rblRequireLogin As Global.System.Web.UI.WebControls.RadioButtonList

    '''<summary>
    '''pnlLoginColumns control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlLoginColumns As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''lsbLoginColumns control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lsbLoginColumns As Global.System.Web.UI.WebControls.ListBox

    '''<summary>
    '''rfvEmailSubmitter control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rfvEmailSubmitter As Global.System.Web.UI.WebControls.RequiredFieldValidator

    '''<summary>
    '''rblEmailSubmitter control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rblEmailSubmitter As Global.System.Web.UI.WebControls.RadioButtonList

    '''<summary>
    '''pnlEmailSubmitter control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlEmailSubmitter As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''rptEmailRecipients control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rptEmailRecipients As Global.System.Web.UI.WebControls.Repeater

    '''<summary>
    '''btnAddEmail control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnAddEmail As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''cblAdditionalOperationTypes control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cblAdditionalOperationTypes As Global.System.Web.UI.WebControls.CheckBoxList

    '''<summary>
    '''AdditionalOperationTabs control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents AdditionalOperationTabs As Global.AjaxControlToolkit.TabContainer

    '''<summary>
    '''AfterPageLoad control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents AfterPageLoad As Global.AjaxControlToolkit.TabPanel

    '''<summary>
    '''rptAfterPageLoad control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rptAfterPageLoad As Global.System.Web.UI.WebControls.Repeater

    '''<summary>
    '''AfterPageSubmit control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents AfterPageSubmit As Global.AjaxControlToolkit.TabPanel

    '''<summary>
    '''rptAfterPageSubmit control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rptAfterPageSubmit As Global.System.Web.UI.WebControls.Repeater

    '''<summary>
    '''PageHeader control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PageHeader As Global.AjaxControlToolkit.TabPanel

    '''<summary>
    '''rptPageHeader control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rptPageHeader As Global.System.Web.UI.WebControls.Repeater

    '''<summary>
    '''BeforePageLoad control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BeforePageLoad As Global.AjaxControlToolkit.TabPanel

    '''<summary>
    '''rptBeforePageLoad control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rptBeforePageLoad As Global.System.Web.UI.WebControls.Repeater

    '''<summary>
    '''CommonMethods control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CommonMethods As Global.AjaxControlToolkit.TabPanel

    '''<summary>
    '''txtCommonMethods control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtCommonMethods As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''PageMethods control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PageMethods As Global.AjaxControlToolkit.TabPanel

    '''<summary>
    '''rptPageMethods control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rptPageMethods As Global.System.Web.UI.WebControls.Repeater

    '''<summary>
    '''Imports control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents [Imports] As Global.AjaxControlToolkit.TabPanel

    '''<summary>
    '''txtImports control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtImports As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''BeforePageSubmit control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BeforePageSubmit As Global.AjaxControlToolkit.TabPanel

    '''<summary>
    '''rptBeforePageSubmit control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rptBeforePageSubmit As Global.System.Web.UI.WebControls.Repeater

    '''<summary>
    '''SupervisorsContainer control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SupervisorsContainer As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''cvSupervisors control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cvSupervisors As Global.System.Web.UI.WebControls.CustomValidator

    '''<summary>
    '''rptSupervisors control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rptSupervisors As Global.System.Web.UI.WebControls.Repeater

    '''<summary>
    '''btnrptSupervisorsAddItem control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnrptSupervisorsAddItem As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''rfvEmailSupervisor control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rfvEmailSupervisor As Global.System.Web.UI.WebControls.RequiredFieldValidator

    '''<summary>
    '''rblEmailSupervisor control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rblEmailSupervisor As Global.System.Web.UI.WebControls.RadioButtonList

    '''<summary>
    '''pnlPages control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlPages As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''rfvMultipleSubmissions control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rfvMultipleSubmissions As Global.System.Web.UI.WebControls.RequiredFieldValidator

    '''<summary>
    '''rblMultipleSubmissions control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rblMultipleSubmissions As Global.System.Web.UI.WebControls.RadioButtonList

    '''<summary>
    '''pnlRetainedColumns control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlRetainedColumns As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''lblMainTableName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblMainTableName As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lsbMainColumns control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lsbMainColumns As Global.System.Web.UI.WebControls.ListBox

    '''<summary>
    '''rptTables control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rptTables As Global.System.Web.UI.WebControls.Repeater

    '''<summary>
    '''PagesContainer control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PagesContainer As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''cvPages control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cvPages As Global.System.Web.UI.WebControls.CustomValidator

    '''<summary>
    '''rptPages control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rptPages As Global.System.Web.UI.WebControls.Repeater

    '''<summary>
    '''btnrptPagesAddItem control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnrptPagesAddItem As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''chkCustomConfirmationPageMessage control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkCustomConfirmationPageMessage As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''pnlConfirmationPageMessage control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlConfirmationPageMessage As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''rblConfirmationPageMessageType control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rblConfirmationPageMessageType As Global.System.Web.UI.WebControls.RadioButtonList

    '''<summary>
    '''txtConfirmationPageMessageRich control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtConfirmationPageMessageRich As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtConfirmationPageMessagePlain control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtConfirmationPageMessagePlain As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''pnlShowCustomStatusPageMessage control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlShowCustomStatusPageMessage As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''chkCustomStatusPagemessage control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkCustomStatusPagemessage As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''pnlStatusPageMessage control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlStatusPageMessage As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''rblStatusPageMessageType control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rblStatusPageMessageType As Global.System.Web.UI.WebControls.RadioButtonList

    '''<summary>
    '''txtStatusPageMessageRich control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtStatusPageMessageRich As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtStatusPageMessagePlain control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtStatusPageMessagePlain As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''btnContinue control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnContinue As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''vsWebRAD control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents vsWebRAD As Global.System.Web.UI.WebControls.ValidationSummary
End Class
