'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class indexnew
    
    '''<summary>
    '''ddlCurrentProject control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlCurrentProject As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''rfvPageTitle control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rfvPageTitle As Global.System.Web.UI.WebControls.RequiredFieldValidator
    
    '''<summary>
    '''txtPageTitle control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtPageTitle As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''rfvDepartmentName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rfvDepartmentName As Global.System.Web.UI.WebControls.RequiredFieldValidator
    
    '''<summary>
    '''ddlDepartmentName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlDepartmentName As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''lblOptions control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblOptions As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''cblOptions control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cblOptions As Global.System.Web.UI.WebControls.CheckBoxList
    
    '''<summary>
    '''pnlCustomDepartmentName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlCustomDepartmentName As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''rfvCustomDepartmentName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rfvCustomDepartmentName As Global.System.Web.UI.WebControls.RequiredFieldValidator
    
    '''<summary>
    '''txtCustomDepartmentName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtCustomDepartmentName As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''pnlEcommerce control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlEcommerce As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''rfvEcommerceProduct control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rfvEcommerceProduct As Global.System.Web.UI.WebControls.RequiredFieldValidator
    
    '''<summary>
    '''ddlEcommerceProduct control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlEcommerceProduct As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''rfvDefaultCharge control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rfvDefaultCharge As Global.System.Web.UI.WebControls.RequiredFieldValidator
    
    '''<summary>
    '''rblDefaultCharge control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rblDefaultCharge As Global.System.Web.UI.WebControls.RadioButtonList
    
    '''<summary>
    '''pnlDefaultCharge control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlDefaultCharge As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''rfvDefaultChargeText control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rfvDefaultChargeText As Global.System.Web.UI.WebControls.RequiredFieldValidator
    
    '''<summary>
    '''cmpDefaultChargeText control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmpDefaultChargeText As Global.System.Web.UI.WebControls.CompareValidator
    
    '''<summary>
    '''txtDefaultCharge control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtDefaultCharge As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''pnlWorkflow control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlWorkflow As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''rfvWorkflowStep control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rfvWorkflowStep As Global.System.Web.UI.WebControls.RequiredFieldValidator
    
    '''<summary>
    '''ddlWorkflowStep control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlWorkflowStep As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''rfvSQLServer control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rfvSQLServer As Global.System.Web.UI.WebControls.RequiredFieldValidator
    
    '''<summary>
    '''ddlSQLServer control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlSQLServer As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''rfvSQLDatabase control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rfvSQLDatabase As Global.System.Web.UI.WebControls.RequiredFieldValidator
    
    '''<summary>
    '''ddlSQLDatabase control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlSQLDatabase As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''rfvSQLMainTableName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rfvSQLMainTableName As Global.System.Web.UI.WebControls.RequiredFieldValidator
    
    '''<summary>
    '''txtSQLMainTableName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtSQLMainTableName As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''rfvSQLInsertStoredProcedureName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rfvSQLInsertStoredProcedureName As Global.System.Web.UI.WebControls.RequiredFieldValidator
    
    '''<summary>
    '''txtSQLInsertStoredProcedureName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtSQLInsertStoredProcedureName As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''rfvSQLUpdateStoredProcedureName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rfvSQLUpdateStoredProcedureName As Global.System.Web.UI.WebControls.RequiredFieldValidator
    
    '''<summary>
    '''txtSQLUpdateStoredProcedureName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtSQLUpdateStoredProcedureName As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtSQLAdditionalCertificationStatement control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtSQLAdditionalCertificationStatement As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''btnContinue control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnContinue As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''vsWebRAD control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents vsWebRAD As Global.System.Web.UI.WebControls.ValidationSummary
End Class
