'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

''Option Strict Off
Option Explicit On


Partial Public Class WebRADListItems
    
    '''<summary>
    '''pnlSelectionItems control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlSelectionItems As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''rfvSelectionItems control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rfvSelectionItems As Global.System.Web.UI.WebControls.RequiredFieldValidator
    
    '''<summary>
    '''pnlSelectionItemsRequired control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlSelectionItemsRequired As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''ddlSelectionItems control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlSelectionItems As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''pnlListItems control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlListItems As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''rfvListItems control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rfvListItems As Global.System.Web.UI.WebControls.RequiredFieldValidator
    
    '''<summary>
    '''pnlListItemsRequired control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlListItemsRequired As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''ddlListItems control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlListItems As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''rptListItems control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rptListItems As Global.System.Web.UI.WebControls.Repeater
    
    '''<summary>
    '''lblListItemCount control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblListItemCount As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''pnlDataMethod control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlDataMethod As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''rfvDataMethod control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rfvDataMethod As Global.System.Web.UI.WebControls.RequiredFieldValidator
    
    '''<summary>
    '''ddlDataMethod control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlDataMethod As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''pnlOtherDataMethod control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlOtherDataMethod As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''rfvOtherDataMethod control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rfvOtherDataMethod As Global.System.Web.UI.WebControls.RequiredFieldValidator
    
    '''<summary>
    '''txtOtherDataMethod control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtOtherDataMethod As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''pnlIncludePleaseSelect control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlIncludePleaseSelect As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''rfvIncludePleaseSelect control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rfvIncludePleaseSelect As Global.System.Web.UI.WebControls.RequiredFieldValidator
    
    '''<summary>
    '''rblIncludePleaseSelect control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rblIncludePleaseSelect As Global.System.Web.UI.WebControls.RadioButtonList
    
    '''<summary>
    '''pnlMinimumValue control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlMinimumValue As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''rfvMinimumValue control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rfvMinimumValue As Global.System.Web.UI.WebControls.RequiredFieldValidator
    
    '''<summary>
    '''pnlMinimumValueRequired control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlMinimumValueRequired As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''txtMinimumValue control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtMinimumValue As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''pnlMaximumValue control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlMaximumValue As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''rfvMaximumValue control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rfvMaximumValue As Global.System.Web.UI.WebControls.RequiredFieldValidator
    
    '''<summary>
    '''pnlMaximumValueRequired control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlMaximumValueRequired As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''txtMaximumValue control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtMaximumValue As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''ucDataSource control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ucDataSource As Global.stable.WebRADDataSource
End Class
