'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

''Option Strict Off
Option Explicit On


Partial Public Class TopMenuNew
    
    '''<summary>
    '''ddlProjects control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlProjects As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''libMainDetails control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents libMainDetails As Global.System.Web.UI.WebControls.LinkButton
    
    '''<summary>
    '''libControlDetails control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents libControlDetails As Global.System.Web.UI.WebControls.LinkButton
    
    '''<summary>
    '''libFrontendDetails control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents libFrontendDetails As Global.System.Web.UI.WebControls.LinkButton
    
    '''<summary>
    '''libBackendDetails control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents libBackendDetails As Global.System.Web.UI.WebControls.LinkButton
    
    '''<summary>
    '''libFinalize control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents libFinalize As Global.System.Web.UI.WebControls.LinkButton
End Class
