'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class TriggerValues
    
    '''<summary>
    '''rfvNumberTriggerValues control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rfvNumberTriggerValues As Global.System.Web.UI.WebControls.RequiredFieldValidator
    
    '''<summary>
    '''ddlNumberTriggerValues control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlNumberTriggerValues As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''rptTriggerValues control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rptTriggerValues As Global.System.Web.UI.WebControls.Repeater
End Class
