'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic
Imports WhitTools.SQL

Partial Public Class ProjectControl
    Public Function GetSQLDefaultValue() As String
        Dim returnValue As String = ""

        If If(SQLDefaultValueType, "Text") = "Text" Then
            If SQLDefaultValue = "NULL" Or If(SQLDefaultValue, "") = "" Then
                returnValue = "NULL"
            Else
                returnValue = "'" & CleanSQL(SQLDefaultValue) & "'"
            End If
        Else
            returnValue = SQLDefaultValue
        End If

        Return " " & returnValue
    End Function
End Class
