'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class ARA_Assignments
    Public Property ID As Integer
    Public Property RuleID As Nullable(Of Integer)
    Public Property DepID As Nullable(Of Integer)
    Public Property PLID As String

    Public Overridable Property ARA_Departments As ARA_Departments
    Public Overridable Property ARA_Rules As ARA_Rules

End Class
