'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class ARA_Rules
    Public Property ID As Integer
    Public Property Type As Nullable(Of Integer)
    Public Property ShortDescription As String
    Public Property Description As String
    Public Property LastModifiedBy As String
    Public Property LastModified As Nullable(Of Date)
    Public Property SubmittedBy As String
    Public Property DateSubmitted As Nullable(Of Date)

    Public Overridable Property ARA_Assignments As ICollection(Of ARA_Assignments) = New HashSet(Of ARA_Assignments)

End Class
