'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class ARA_Schools
    Public Property ID As Integer
    Public Property Description As String
    Public Property School As String
    Public Property Type As Nullable(Of Integer)
    Public Property AddressLine1 As String
    Public Property AddressLine2 As String
    Public Property City As String
    Public Property State As String
    Public Property ZIP As String
    Public Property Country As String
    Public Property Website As String
    Public Property Phone As String
    Public Property Email As String
    Public Property CEEB As String
    Public Property Local As Nullable(Of Integer)
    Public Property RedirectTo As Nullable(Of Integer)

End Class
