'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class ARA_MajorCategories
    Public Property ID As Integer
    Public Property Category As String
    Public Property DepID As Nullable(Of Integer)
    Public Property Active As Nullable(Of Integer)

End Class
