'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class ARA_Majors
    Public Property ID As Integer
    Public Property Major As String
    Public Property Code As String
    Public Property CategoryID As Nullable(Of Integer)
    Public Property Active As Nullable(Of Boolean)
    Public Property FreshmanProgram As Nullable(Of Integer)
    Public Property DatawarehouseDescription As String

End Class
