'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Data.Entity
Imports System.Data.Entity.Infrastructure

Partial Public Class CommunicationsEntities
    Inherits DbContext

    Public Sub New()
        MyBase.New("name=CommunicationsEntities")
    End Sub

    Protected Overrides Sub OnModelCreating(modelBuilder As DbModelBuilder)
        Throw New UnintentionalCodeFirstException()
    End Sub

    Public Overridable Property ARA_Assignments() As DbSet(Of ARA_Assignments)
    Public Overridable Property ARA_CabinetDepartments() As DbSet(Of ARA_CabinetDepartments)
    Public Overridable Property ARA_CabinetList() As DbSet(Of ARA_CabinetList)
    Public Overridable Property ARA_Department_BreadcrumbLinks() As DbSet(Of ARA_Department_BreadcrumbLinks)
    Public Overridable Property ARA_Departments() As DbSet(Of ARA_Departments)
    Public Overridable Property ARA_Departments_Locations() As DbSet(Of ARA_Departments_Locations)
    Public Overridable Property ARA_DepartmentTypes() As DbSet(Of ARA_DepartmentTypes)
    Public Overridable Property ARA_DepChairList() As DbSet(Of ARA_DepChairList)
    Public Overridable Property ARA_DepChairList_SubDepartments() As DbSet(Of ARA_DepChairList_SubDepartments)
    Public Overridable Property ARA_DepDirectorsDeansList() As DbSet(Of ARA_DepDirectorsDeansList)
    Public Overridable Property ARA_DepDirectorsDeansList_SubDepartments() As DbSet(Of ARA_DepDirectorsDeansList_SubDepartments)
    Public Overridable Property ARA_DepDirectorsDeansList_Types() As DbSet(Of ARA_DepDirectorsDeansList_Types)
    Public Overridable Property ARA_MajorCategories() As DbSet(Of ARA_MajorCategories)
    Public Overridable Property ARA_Majors() As DbSet(Of ARA_Majors)
    Public Overridable Property ARA_Rules() As DbSet(Of ARA_Rules)
    Public Overridable Property ARA_RuleTypes() As DbSet(Of ARA_RuleTypes)
    Public Overridable Property ARA_Schools() As DbSet(Of ARA_Schools)
    Public Overridable Property ARA_StatesProvinces() As DbSet(Of ARA_StatesProvinces)
    Public Overridable Property ARA_VPDepartments() As DbSet(Of ARA_VPDepartments)
    Public Overridable Property ARA_VPList() As DbSet(Of ARA_VPList)

End Class
