'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class ProjectDataSource
    Public Property ID As Integer
    Public Property ParentType As Nullable(Of Integer)
    Public Property Source As String
    Public Property BackendSource As String
    Public Property Column As String
    Public Property Type As Nullable(Of Integer)
    Public Property [Select] As String
    Public Property Table As String
    Public Property Where As String
    Public Property GroupBy As String
    Public Property OrderBy As String
    Public Property TextField As String
    Public Property ValueField As String

    Public Overridable Property DataSourceParentType As DataSourceParentType
    Public Overridable Property ProjectBackendExports As ICollection(Of ProjectBackendExport) = New HashSet(Of ProjectBackendExport)
    Public Overridable Property ProjectControls As ICollection(Of ProjectControl) = New HashSet(Of ProjectControl)

End Class
