'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class TableHierarchy
    Public Property ID As Integer
    Public Property TableName As String
    Public Property ParentID As Nullable(Of Integer)
    Public Property ForeignID As Nullable(Of Integer)

End Class
